### PR TITLE
Fix flexible sidebar

### LINKED ISSUE #185: sidebar doesn't go to the bottom of the page
sidebar-height-bug

the following css might the issue
```
html, body, .wrapper {
  height: 100%
}
```

### PR DESCRIPTION
**Pull request by boney-bun**
fix #185

### CODE REVIEW

**Comment by boney-bun** [comment]
@pierrealixt i can't find a way to satisfy both two cases:
- the content of right panel is taller than window height
- the content of right panel is shorter than window height

this PR is to satisfy the first case, but fail on the second one.

i'm thinking to set the height of the sidebar to window's height, then add scroll in the right panel when the content is taller than window height. what do you think?

**Comment by pierrealixt** [comment]
I think this code might be the issue:
```
html, body, .wrapper {
    min-height: 100% !important;
    height: auto !important; /* cross-browser */ 
    height: 100%;
}
```

**Comment by pierrealixt** [comment]
@boney-bun Here's an example of a fixed sidebar with Bootstrap: https://getbootstrap.com/docs/4.3/examples/dashboard/

**Review by pierrealixt — CHANGES_REQUESTED** [review]
See https://getbootstrap.com/docs/4.3/examples/dashboard/

**Comment by pierrealixt** [comment]
This seems to be fixed in `develop`.
@Christiaanvdm do you confirm that you fixed it in one your PR?

**Pull request closed without merging**
