### PR TITLE
temporary hide radial progress bar

### LINKED ISSUE #316: Hide the radial progress bar

### PR DESCRIPTION
**Pull request by boney-bun**
fix #316

### CODE REVIEW

**Comment by boney-bun** [comment]
the layout with 6 campuses:
Screen Shot 2019-05-07 at 11 15 20 AM

**Comment by pierrealixt** [comment]
It doesn't look that great?
What do you think @boney-bun, @Christiaanvdm ?

**Comment by boney-bun** [comment]
yeah, agree...particularly the empty space in the center.
i just did it according to our last meeting.
perhaps adding the provider logo?
otherwise, i think this is only temporary solution until we have a working progress bar.

**Comment by pierrealixt** [comment]
what about making that div smaller? I know it's an image but you can easily make it in css.
Adding the provider'logo? that would be too much. The campus all belong to the same provider.

**Comment by boney-bun** [comment]
something like this?
Screen Shot 2019-05-07 at 1 23 30 PM

**Comment by pierrealixt** [comment]
Yeah we could add some useful informations like:
- the number of events
- the number of qualifications

I'll create a ticket for those.

**Review by pierrealixt — APPROVED** [review]
LGTM

**Pull request merged**
