### PR TITLE
hide sidebar in provider form, show it in provider edit form

### LINKED ISSUE #226: Do not collapse the sidebar. Always display it. Hide it on the provider form.

### PR DESCRIPTION
**Pull request by boney-bun**
fix #226

### CODE REVIEW

**Comment by boney-bun** [comment]
this PR will only affect the sidebar in the provider pages. the other pages always show sidebar:
ford3#247

the current behaviour in the server:
ford3#247_server

Note:
*Edited from original*
@pierrealixt @Christiaanvdm surprisingly i found two extra enclosed div (`</div>`) in the provider_form.html and lack one extra enclosed div in the provider.html. i have removed and added them accordingly.

**Comment by pierrealixt** [comment]
@boney-bun I don't think you understand correctly what I meant:
> Do not collapse the sidebar. 

Here I meant that we should not use javascript to show the sidebar. (see `sidebar.js`)

> Always display it. 

Always display the sidebar, on every page.

> Hide it on the provider form

But it should be hidden on the provider form (`providers/provider_id/edit`)


And what is, for you, the difference between the provider form and the provider edit form?

**Comment by boney-bun** [comment]
> Here I meant that we should not use javascript to show the sidebar. (see sidebar.js)

@pierrealixt cmmiw, sidebar.js define a function call toggleSidebar().
it has also onclick event that seems to be called on the test_widgets only
ok, so what's provider.js for?
i got impression that you would like to remove sidebar.js instead. am i right?

> Always display the sidebar, on every page.
is it the current version always display sidebar (except on provider edit page)?

> But it should be hidden on the provider form (providers/provider_id/edit)
> And what is, for you, the difference between the provider form and the provider edit form?

i think we have different perspective. 
to me, provider form is to show provider only (providers/provider_id).
provider edit form is to edit the provider (providers/provider_id/edit).

@pierrealixt i think a zoom can clear things out

**Review by pierrealixt — APPROVED** [review]
LGTM

**Pull request merged**
