### PR TITLE
centered openedu logo between the sidebar

### LINKED ISSUE #311: OpenEdu logo is not centered

### PR DESCRIPTION
**Pull request by boney-bun**
fix #311

### CODE REVIEW

**Comment by boney-bun** [comment]
PIA:
ford3#371

**Comment by pierrealixt** [comment]
@boney-bun Can you check the landing page as well?

**Comment by boney-bun** [comment]
@pierrealixt yes, you're right.
i should anticipate the logo in the landing page as well.
i also put the admin link to be always right-aligned.

PIA:
ford3#371_revision

**Review by pierrealixt — APPROVED** [review]
LGTM

**Pull request merged**
