### PR TITLE
Added sidebar to provider view

### LINKED ISSUE #147: add the sidebar

### PR DESCRIPTION
**Pull request by Christiaanvdm**
This closes #147
image

### CODE REVIEW

**Comment by pierrealixt** [comment]
@Christiaanvdm I would not call this file `provider_landing_page` but something like `sidebar.js`:

```
const toggleSidebar = () => {
  const sidebar = document.getElementById('sidebar')
  sidebar.classList.toggle('active')
}

(function () {
  toggleSideBar()
})()
```

What about showing the list of the provider's campus?
In `side_bar.html`, the name of the provider is hard-coded.

**Comment by Christiaanvdm** [comment]
> @Christiaanvdm I would not call this file `provider_landing_page` but something like `sidebar.js`:
> 
> ```
> const toggleSidebar = () => {
>   const sidebar = document.getElementById('sidebar')
>   sidebar.classList.toggle('active')
> }
> 
> (function () {
>   toggleSideBar()
> })()

Ok, done.

> What about showing the list of the provider's campus?
> In `side_bar.html`, the name of the provider is hard-coded.

I made an issue for this https://github.com/kartoza/ford3/issues/169

**Comment by pierrealixt** [comment]
@Christiaanvdm Have you read `side_bar.html`?
https://github.com/kartoza/ford3/blob/develop/django_project/core/base_templates/side_navbar.html

**Comment by pierrealixt** [comment]
I know I'm being picky but just let's call the provider template file: `provider.html` instead of `provider_landing_page.html`

**Comment by Christiaanvdm** [comment]
> @Christiaanvdm Have you read `side_bar.html`?
> https://github.com/kartoza/ford3/blob/develop/django_project/core/base_templates/side_navbar.html

Yes, it needs work. Let us do the side_navbar stuff in #169 and just isolate this refactoring with this PR?

**Comment by Christiaanvdm** [comment]
> I know I'm being picky but just let's call the provider template file: `provider.html` instead of `provider_landing_page.html`

You are allowed to be picky, especially when I agree with you 👍 Done.

**Review by pierrealixt — APPROVED** [review]
LGTM

**Pull request merged**
