### PR TITLE
change dimension of provider logo into 86x86 in sidebar

### LINKED ISSUE #228: sidebar provider logo is too big
In the mockups:
Screen Shot 2019-04-16 at 17 20 15

In FORD3:
Screen Shot 2019-04-16 at 17 20 35

### PR DESCRIPTION
**Pull request by boney-bun**
fix #228

### CODE REVIEW

**Comment by boney-bun** [comment]
the logo in sidebar is now smaller:
Screen Shot 2019-04-18 at 3 40 08 PM

**Comment by pierrealixt** [comment]
Have you checked your changes didnt affect the provider form?
I havent checked avocode but what's the sizing of the logo in the provider form?

**Comment by boney-bun** [comment]
this in provider form:
Screen Shot 2019-04-18 at 3 54 52 PM

**Comment by pierrealixt** [comment]
@boney-bun the latest screenshot you posted is not the provider form. 
The provider form is accessible at this url: `providers/provider_id/edit`

**Review by pierrealixt — APPROVED** [review]
LGTM

**Pull request merged**
