### PR TITLE
prevent the removal of a campus in provider form

### LINKED ISSUE #181: provider initialization: form must be submitted with at least one campus
I could submit a provider form without a campus (I clicked on the 'remove campus input').

### PR DESCRIPTION
**Pull request by boney-bun**
fix #181

### CODE REVIEW

**Comment by boney-bun** [comment]
PIA:
ford3#181

**Review by pierrealixt — COMMENTED** [review]
It's weird that Travis is failing.
Could you please rebase your PR following this procedure https://docs.google.com/document/d/1fnYSKwYC3jrUKt8CkNQeepnB8yBgbUG9JB3GJzLVOCY/edit?usp=sharing

Make sure `make test` runs fine before pushing. In your case you only modified one javascript file so the tests should not fail.

**Comment by boney-bun** [comment]
@pierrealixt yes, i'm aware of it too.

i'd fixed the travis error last night. 
the last commit (e47f966497c9b91ddd795810d220e847f9f81373) contain fixing error on travis.

i have merged this branch with the last commit from develop branch.
now it's green.
could i merge it?

**Review by pierrealixt — APPROVED** [review]
LGTM

**Comment by boney-bun** [comment]
thanks @pierrealixt 
i'm going to merge this

**Pull request merged**
