### PR TITLE
Change phone field

### LINKED ISSUE #427: Telephone Number field insufficent characters
http://ford3.kartoza.com/ford3/providers/10/edit

input field labelled Telephone number is limited to 12 numbers.  this needs to be extended to allow for international codes, etc.  Other telephone fields are longer

### PR DESCRIPTION
**Pull request by boney-bun**
fix #427

### CODE REVIEW

**Comment by boney-bun** [comment]
the business rule:
- the phone must at least 10 to 15 digits
- the phone can start with a plus (`+`) sign followed by country code
- no space allowed

is there anything i missed?

PIA:
ford3#427

**Comment by pierrealixt** [comment]
There is another phone number in the campus form.

**Comment by boney-bun** [comment]
yes.
if we agree with the business rule above, i'll do the same to all phone fields in the forms.

can we use the above business rule for phone field?

**Comment by pierrealixt** [comment]
yes

**Comment by boney-bun** [comment]
@Pierre-Alix i have added the phone into campus and prospect. 
the phone validation works in prospect, but not in campus form. 
it turns out that the `form.is_valid` method is never get called (except in the render_done). 
so the validation is not working properly. 

i think we need to create a new issue for the validation stuff.

**Review by pierrealixt — APPROVED** [review]
LGTM

**Review by pierrealixt — CHANGES_REQUESTED** [review]
Fix flake8 issue

**Review by pierrealixt — APPROVED** [review]
LGTM

**Pull request merged**
