### PR TITLE
order campus list alphabetically in sidebar

### LINKED ISSUE #321: Campus list on the sidebar is randomly ordered
Order the list alphabetically

### PR DESCRIPTION
**Pull request by boney-bun**
fix #321

### CODE REVIEW

**Comment by boney-bun** [comment]
PIA:
ford3#362

**Comment by pierrealixt** [comment]
Ok this ticket is about ordering the campus list in the sidebar but let's try to be consistent here: the campus on the campus page are not ordered the same way as in the sidebar.

**Comment by boney-bun** [comment]
yes, that's why i created #363.
do you want me to do it while i'm on it?

**Comment by pierrealixt** [comment]
yes @boney-bun

**Pull request closed without merging**
