### PR TITLE
Link campus form step4 157

### LINKED ISSUE #157: Have a direct link to campus qualifications form (step 4)
We'll add a button on the campus page that goes directly to the step 4 of the campus form (Qualification manager)

### PR DESCRIPTION
**Pull request by pierrealixt**
Fixed #157 
gotostep4

### CODE REVIEW

**Review by Christiaanvdm — APPROVED** [review]
LGTM

**Comment by boney-bun** [comment]
@pierrealixt just UI question: i think the `edit qualification` button is too big compare to the above `edit` button. maybe they need to be of the same size?

**Comment by pierrealixt** [comment]
Screen Shot 2019-05-09 at 07 57 46

@boney-bun better?

**Comment by boney-bun** [comment]
@pierrealixt yes, much better now

**Pull request merged**
