### PR TITLE
add default value of 1000 to annual student capacity field

### LINKED ISSUE #428: Annual Student Capacity increment counter
http://ford3.kartoza.com/ford3/providers/10/campus/53/edit

The first time you use the up or down arrows to increment the default Annual Student Capacity it moves the value to 1 - even if the default is 1000.  

If you manually enter 1000, and then use the increment tool, it does work properly

### PR DESCRIPTION
**Pull request by boney-bun**
fix #428

### CODE REVIEW

**Comment by boney-bun** [comment]
i think March misunderstood between the placeholder and default value.
*1000* in the field is from the placeholder, not the default value. 
so i think the current behaviour is expected.

but, if we would like to have the behaviour as described by March, then this PR will fix it.

PIA:
ford3#481

**Comment by pierrealixt** [comment]
I think it should be a placeholder, not a default value.

**Comment by pierrealixt** [comment]
Ok I see why March got lost.
The style of the placeholder is misleading, the `1000` is less grey than the placeholder for the e-mail address.

So to fix this:
- change the placeholder to `e.g: 1000`
- add styling so it looks like the other placeholders

**Review by pierrealixt — APPROVED** [review]
LGTM

**Comment by boney-bun** [comment]
the placeholders's style is now equal to the other two fields above it:
Screen Shot 2019-05-31 at 2 21 11 PM

**Pull request merged**
