### PR TITLE
put action buttons side by side

### LINKED ISSUE #265: Put these actions side by side
Campus view
image

### PR DESCRIPTION
**Pull request by boney-bun**
fix #265

### CODE REVIEW

**Comment by boney-bun** [comment]
PIA:
Screen Shot 2019-04-28 at 8 10 01 AM

**Comment by timlinux** [comment]
Please attach a screenie to your PR

**Comment by timlinux** [comment]
LGTM

**Review by Christiaanvdm — APPROVED** [review]
LGTM

**Pull request merged**
